version: "3.9"

services:
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
